### ISSUE TITLE
SPKI-based construction

### ISSUE THREAD

**Issue by chris-wood** [jedisct1/rust-blind-rsa-signatures#4]
Per [the spec](https://cfrg.github.io/draft-irtf-cfrg-blind-signatures/draft-irtf-cfrg-rsa-blind-signatures.html#name-public-key-certification), it would be great if one could construct public keys from DER or PEM encoded SPKI values with the RSASSA-PSS OID. Would you be open to adding such a feature?

**Comment by jedisct1** [comment]
The Zig and C implementations can already export public keys as SPKI values with the RSASSA-PSS OID.

So yes, I'd definitely be open to adding SPKI support in the Rust implementation as well. And importation in other implementations would be nice to have, too!
